apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-service
  labels:
    app: follow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow-service
  template:
    metadata:
      labels:
        app: follow-service
    spec:
      containers:
      - name: follow-service
        image: quittercr.azurecr.io/follow-service:v0.4.0
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: follow-env
---
apiVersion: v1
kind: Service
metadata:
  name: follow-service
spec:
  selector:
    app: follow-service
  ports:
    - protocol: TCP
      port: 5003