apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: localhost:5000/gateway:v0.2.9
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 500Mi
            cpi: 500m
        ports:
        - containerPort: 3000