version: "3.7"

services:
  db:
    platform: linux/x86_64
    container_name: 'quitter-database'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_HOST: localhost
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes: 
      - ./docker:/docker-entrypoint-initdb.d:z
  gateway:
    depends_on: ["db"]
    image: gateway
    restart: unless-stopped
    build:
      context: ./gateway
      dockerfile: ./dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
  queet-service:
    depends_on: ["gateway"]
    image: queet-service
    restart: unless-stopped
    build:
      context: ./microservices/queet-service
    environment:
      MYSQL_HOST: "mysql"
    ports:
      - "5001:5001"
  user-service:
    depends_on: ["queet-service"]
    image: user-service
    restart: unless-stopped
    build:
      context: ./microservices/user-service
    environment:
      MYSQL_HOST: "mysql"
    ports:
      - "5002:5002"
volumes:
  db-data: