# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Follow service CI

on:
  push:
    paths:
      - 'src/microservices/follow-service/**'
    branches: 
      - development
      - master
      - feat/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build stage
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './src/microservices/follow-service'

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./src/microservices/follow-service/package-lock.json
    - name: Run CI
      working-directory: ./src/microservices/follow-service
      run: npm ci
    - name: Run build
      working-directory: ./src/microservices/follow-service
      run: npm run build --if-present
    
      
  test:
    needs: [build]
    name: Test stage
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './src/microservices/follow-service'
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./src/microservices/follow-service/package-lock.json
    - name: Run CI
      working-directory: ./src/microservices/follow-service
      run: npm ci
    - name: Run test
      working-directory: ./src/microservices/follow-service
      run: npm test   
