# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    paths:
      - 'src/Frontend/**'
    branches: 
      - development
      - master
      - feat/**
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './src/Frontend'

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./src/Frontend/package-lock.json
    - name: Run CI
      working-directory: ./src/Frontend
      run: npm ci --force
    - name: Run build
      working-directory: ./src/Frontend
      run: npm run build --if-present
    
      
  test:
    needs: [build]
    name: Test stage
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './src/Frontend'
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./src/Frontend/package-lock.json
    - name: Run CI
      working-directory: ./src/Frontend
      run: npm ci
    # - name: Run test
    #   working-directory: ./src/Frontend
    #   run: npm run test-headless
    # Disabled due to stuck in chrome binding
