# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gateway CI

on:
  push:
    paths:
      - 'src/gateway/**'
    branches: 
      - development
      - master
      - feat/**
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './src/gateway'

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        working-directory: ./src/gateway
    - name: Run CI
      working-directory: ./src/gateway
      run: npm ci
    - name: Run build
      working-directory: ./src/gateway
      run: npm run build --if-present
    - name: Run test
      working-directory: ./src/gateway
      run: npm test
