apiVersion: apps/v1
kind: Deployment
metadata:
  name: queet-service
  labels:
    app: queet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queet-service
  template:
    metadata:
      labels:
        app: queet-service
    spec:
      containers:
      - name: queet-service
        image: quittercr.azurecr.io/queet-service:v0.4.0
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: queet-service
spec:
  selector:
    app: queet-service
  ports:
    - protocol: TCP
      port: 5001