apiVersion: apps/v1
kind: Deployment
metadata:
  name: queet-service
  labels:
    app: queet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queet-service
  template:
    metadata:
      labels:
        app: queet-service
    spec:
      containers:
      - name: queet-service
        image: localhost:5000/queet-service:v0.2.8
        resources:
          limits:
            memory: 500Mi
            cpi: 500m
        ports:
        - containerPort: 5001